# Define the Twitter API configuration.
TWITTER_CONSUMER_KEY = "TODO"
TWITTER_CONSUMER_SECRET = "TODO"
TWITTER_ACCESS_TOKEN = "TODO"
TWITTER_ACCESS_SECRET = "TODO"

# Define the paths to the models.
KERAS_MODEL_PATH = "TODO"
WORD2VEC_MODEL_PATH = "TODO"

# Define the Google Map API key.
GOOGLE_MAPS_API_KEY = "TODO"
